onmoon/openapi-server-bundle

src/CodeGenerator/Dto/PhpParserRootDtoFactory.php
src/Command/GenerateApiCodeCommand.php

No DTO if no request data

---

src/CodeGenerator/ApiServerCodeGenerator.php
src/Exception/CannotGenerateCodeForOperation.php

Throw exception if root is not an object

---

src/CodeGenerator/ApiServerCodeGenerator.php
src/CodeGenerator/Dto/Definitions/Factory/ResponseDtoDefinitionFactory.php
src/CodeGenerator/Dto/Definitions/ResponseDtoDefinition.php
src/CodeGenerator/Dto/PhpParserDtoFactory.php
src/Controller/ApiController.php
src/Interfaces/ResponseDto.php
src/Serializer/ReflectionDtoSerializer.php

Improved multiple response codes support

---

README.md
src/CodeGenerator/ApiServerCodeGenerator.php
src/CodeGenerator/PhpParserGenerators/CodeGenerator.php
src/CodeGenerator/PhpParserGenerators/DtoCodeGenerator.php
src/CodeGenerator/PhpParserGenerators/InterfaceCodeGenerator.php
src/CodeGenerator/PhpParserGenerators/ServiceSubscriberCodeGenerator.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OpenApiServerExtension.php
src/Resources/config/services.xml

Removed code used to generate same files as before refactoring

---

src/CodeGenerator/Definitions/OperationDefinition.php
src/CodeGenerator/Definitions/RequestHandlerInterfaceDefinition.php
src/CodeGenerator/FileGenerator.php
src/CodeGenerator/GraphGenerator.php
src/CodeGenerator/InterfaceGenerator.php
src/CodeGenerator/NameGenerator.php
src/CodeGenerator/PhpParserGenerators/InterfaceCodeGenerator.php
src/CodeGenerator/PhpParserGenerators/ServiceSubscriberCodeGenerator.php
src/Controller/ApiController.php
src/Interfaces/ApiLoader.php
src/Specification/Definitions/Operation.php
src/Specification/Definitions/Specification.php
src/Specification/SpecificationLoader.php
src/Specification/SpecificationParser.php
src/Validator/LeaguePSR7RequestSchemaValidator.php

Made controller naming strategy independent

Handler fetch rework

---

README.md
src/CodeGenerator/AttributeGenerator.php
src/CodeGenerator/Definitions/PropertyDefinition.php
src/CodeGenerator/Definitions/RequestDtoDefinition.php
src/CodeGenerator/GraphGenerator.php
src/CodeGenerator/Naming/DefaultNamingStrategy.php
src/CodeGenerator/Naming/NamingStrategy.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OpenApiServerExtension.php
src/Resources/config/services.xml
src/Serializer/ArrayDtoSerializer.php
src/Specification/Definitions/Property.php
src/Specification/SpecificationParser.php

Nullable, ReadOnly, WriteOnly support

---

src/Types/ScalarTypesResolver.php

Closes: #72 
Example: https://3v4l.org/TugEG

Fixed type conversion from bool to string

---

composer.json
test/unit/Types/TypeSerializerTest.php

#85 unit test for type serializer

---

src/Types/ArgumentResolver.php
test/unit/Types/ArgumentResolverTest.php

#83 unit tests for argument resolver

---

test/unit/Event/CodeGenerator/ClassGraphReadyEventTest.php
test/unit/Event/CodeGenerator/FilesReadyEventTest.php
test/unit/Event/Server/RequestDtoEventTest.php
test/unit/Event/Server/RequestEventTest.php
test/unit/Event/Server/ResponseDtoEventTest.php
test/unit/Event/Server/ResponseEventTest.php

Add tests for OnMoon\OpenApiServerBundle\Event

---

composer.json
phpunit.xml.dist
test/unit/CodeGenerator/Definitions/ClassDefinitionTest.php
test/unit/Event/CodeGenerator/ClassGraphReadyEventTest.php
test/unit/Event/CodeGenerator/FilesReadyEventTest.php
test/unit/Event/Server/RequestDtoEventTest.php
test/unit/Event/Server/RequestEventTest.php
test/unit/Event/Server/ResponseDtoEventTest.php
test/unit/Event/Server/ResponseEventTest.php
test/unit/Types/ArgumentResolverTest.php
test/unit/Types/TypeSerializerTest.php

Functional testing setup

---

.github/workflows/mutation-test.yml
composer.json
phpcs.xml.dist
phpstan.neon
phpunit.xml.dist
test/generation/GenerationTestCase.php
test/generation/InMemoryFileWriter.php
test/generation/TestApiServerCodeGeneratorFactory.php
test/generation/Types/TypesGenerationTest.php
test/generation/Types/specification.yaml

Added code generation testing from yaml files

---

.github/workflows/coverage.yml
README.md

Setup code coverage report

---

test/functional/CodeGenerator/Filesystem/FilePutContentsFileWriterTest.php
test/unit/CodeGenerator/Filesystem/FilePutContentsFileWriterTest.php

#95 Functional tests for OnMoon\OpenApiServerBundle\CodeGenerator\Filesystem

---

src/Types/ScalarTypesResolver.php
test/unit/Types/ScalarTypesResolverTest.php

Unit tests for OnMoon\OpenApiServerBundle\Types\ScalarTypesResolver

---

test/unit/CodeGenerator/ApiServerCodeGeneratorTest.php

#100 unit tests for OnMoon\OpenApiServerBundle\CodeGenerator\ApiServerCodeGenerator

---

test/unit/CodeGenerator/Naming/CannotCreateNamespaceTest.php
test/unit/CodeGenerator/Naming/CannotCreatePropertyNameTest.php
test/unit/CodeGenerator/Naming/DefaultNamingStrategyTest.php

#79 Tests for OnMoon\OpenApiServerBundle\CodeGenerator\Naming

---

test/unit/OpenApiServerBundleTest.php

#104 Tests for OnMoon\OpenApiServerBundle\OpenApiServerBundle

---

src/CodeGenerator/InterfaceGenerator.php
test/unit/CodeGenerator/InterfaceGeneratorTest.php

#97 Test for OnMoon\OpenApiServerBundle\CodeGenerator\InterfaceGenerator

---

test/functional/DependencyInjection/ConfigurationTest.php
test/unit/CodeGenerator/PhpParserGenerators/ServiceSubscriberCodeGeneratorTest.php

#111 Tests for OnMoon\OpenApiServerBundle\CodeGenerator\PhpParserGenerators\ServiceSubscriberCodeGenerator

---

composer.json
src/CodeGenerator/NameGenerator.php
src/Controller/ApiController.php
src/Event/Server/RequestDtoEvent.php
test/unit/Event/Server/RequestDtoEventTest.php

Closes https://github.com/onmoon/openapi-server-bundle/issues/175

Changed RequestDtoEvent
